### ISSUE TITLE
Classic notebook extension with 2.0.0

### ISSUE THREAD

**Issue by jtpio** [mamba-org/gator#115]
## Description

It looks like the classic notebook extension is not installed automatically with the latest 2.0.0 release.

## Reproduce

1. `mamba create -n test -c conda-forge python -y`
2. `pip install mamba-gator`
3. `jupyter nbextension list`

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/jtp/miniforge3/envs/test/etc/jupyter/nbconfig
    notebook section
      mamba_gator/static/main  enabled
      - Validating: problems found:
        - require?  X mamba_gator/static/main
    tree section
      mamba_gator/static/tree  enabled
      - Validating: problems found:
        - require?  X mamba_gator/static/tree
```

**Comment by jtpio** [comment]
Ah it's probably because the config points to the file under the `static` dir:

https://github.com/mamba-org/gator/blob/0ad6ce7f9a73577bb9503ba64e59e12271e5952c/jupyter-config/nbconfig/notebook.d/mamba_gator.json#L3

While they are at the top level in the `navigator` folder:

https://github.com/mamba-org/gator/tree/0ad6ce7f9a73577bb9503ba64e59e12271e5952c/mamba_gator/navigator

**Comment by fcollonval** [comment]
Thanks for catching that one. Too much trial to use the same bundle for notebook and the navigator :disappointed: 

When fixing it, it would be good to restore the original test checking the conda tab exists: https://github.com/mamba-org/gator/blob/v3.4.1/jupyter_conda/tests/js/test_notebook_basic.js
