### ISSUE TITLE
Using via JupyterHub?

### ISSUE THREAD

**Issue by Blizzke** [mamba-org/gator#125]
## Description

Not exactly a bug (I presume) but it's giving me headaches nevertheless.
We launch notebooks via JupyterHub and that means the api endpoints are at a different location.

So gator tries to access things like the kernel list via `/api/kernels`. The hub redirects this to `/hub/api/kernels`, but it should use the user routes (`/user/<username>/api/kernels`). Is there any way to get this working?

We used the `jupyterlab_conda` extension so far, which "worked" for us, but that isn't compatible anymore at all. Seems this one comes by default now and it would be awesome to get it to work as it does exactly what we are looking for.

- Python package version: 4.1.0
  
- Extension version:
```
JupyterLab v3.0.5
/opt/conda/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        @mamba-org/gator-lab v2.1.0 enabled  
```

**Comment by fcollonval** [comment]
Hey @Blizzke 

I don't see such error in my company (api end point is correct e.g. https://xxx.jupyter.xxxxx/user/fcollonval/conda/environments?whitelist=0&1611242064442=)

But from your information, you are using the latest JupyterLab for which this package has not been updated yet. So this maybe the reason. Did you use JLab 2 previously? If yes, was it working as expected?

If you could test with the preliminary JLab3 version on that branch - https://github.com/jtpio/gator/tree/lab3 - that would be great.
