### ISSUE TITLE
Option to disable background loading. Performance improvement on JupyterLab startup.

### ISSUE THREAD

**Issue by danilopeixoto** [mamba-org/gator#188]
## Description

Can Gator provide an option to disable background loading?
Mamba Gator is slowing down the JupyterLab at startup.

## Reproduce

`mamba install -y mamba_gator`

1. Go to JupyterLab after startup.

## Expected behavior

Limitating resource usage or option to disable background loading.
A better performance.

## Context

Environment: K8s
CPUs: 2
Memory: 8G

**Comment by fcollonval** [comment]
Thanks for the suggestion @danilopeixoto 

Introducing a new user setting will be best to address this. I can provide pointers if you want to push a PR.

**Comment by danilopeixoto** [comment]
Thanks @fcollonval. Created #190.

**Comment by fcollonval** [comment]
Closing as resolved.
