### ISSUE TITLE
"No web browser found: could not locate runnable browser". Pages refuse to connect to launch Jupyter notebook.

### ISSUE THREAD

**Issue by tedmoorman** [mamba-org/gator#199]
## Description

Using the classical notebook, I receive the following message: "No web browser found: could not locate runnable browser". When clicking on browser extensions given in terminal, pages refuse to connect to launch Jupyter notebook.

Do I need to add some kind of firewall or port forwarding? I do this to create the initial Jupyter notebook that I'm launching from.

## Reproduce

1. Install mamba_gator in conda environment.
2. Activate conda environment.
3. Run 'gator' command.
4. See message: "No web browser found: could not locate runnable browser".
5. Go to IP addresses in terminal, but they refuse to connect.

## Expected behavior

I expected to be able to successfully launch a Jupyter notebook in the browser in which I could use mamba_gator.

## Context

- Python package version:
  mamba_gator 4.1.0
<details><summary>General Information</summary>
<pre>
     active environment : alt
    active env location : /home/xxxxx/.conda/envs/alt
            shell level : 2
       user config file : /home/xxxxx/.condarc
 populated config files : /home/xxxxx/.conda/envs/alt/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /opt/Anaconda3-2019.10  (read only)
           channel URLs : http://xx.xxx.xx.xx:8000/conda-forge/linux-64
                          http://xx.xxx.xx.xx:8000/conda-forge/noarch
                          http://xx.xxx.xx.xx:8000/anaconda/free/linux-64
                          http://xx.xxx.xx.xx:8000/anaconda/free/noarch
                          http://xx.xxx.xx.xx:8000/anaconda/main/linux-64
                          http://xx.xxx.xx.xx:8000/anaconda/main/noarch
          package cache : /opt/Anaconda3-2019.10/pkgs
                          /home/xxxxx/.conda/pkgs
       envs directories : /home/xxxxx/.conda/envs
                          /opt/Anaconda3-2019.10/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/3.10.0-1160.83.1.el7.x86_64 rhel/7.9 glibc/2.17
                UID:GID : 100032:300935
             netrc file : None
           offline mode : False
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
(base) [ ~]$ gator
bash: gator: command not found
(base) [ ~]$ conda activate ~/.conda/envs/alt
(alt) [ ~]$ gator
[I 15:07:36.204 MambaNavigator] The port 8888 is already in use, trying another port.
[I 15:07:36.205 MambaNavigator] The port 8889 is already in use, trying another port.
[I 15:07:36.206 MambaNavigator] The port 8890 is already in use, trying another port.
[I 15:07:36.218 MambaNavigator.mamba_gator] Server extension enabled
[I 15:07:36.222 MambaNavigator] Serving notebooks from local directory: /home/xxxxx
[I 15:07:36.222 MambaNavigator] The Jupyter Notebook is running at:
[I 15:07:36.222 MambaNavigator] http://localhost:8891/?token=df61f3bd9880bc43743354760bb3a8673248cdcaa2329f7a
[I 15:07:36.222 MambaNavigator]  or http://127.0.0.1:8891/?token=df61f3bd9880bc43743354760bb3a8673248cdcaa2329f7a
[I 15:07:36.222 MambaNavigator] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 15:07:36.235 MambaNavigator] No web browser found: could not locate runnable browser.
[C 15:07:36.236 MambaNavigator]
    To access the notebook, open this file in a browser:
        file:///home/xxxxx/.local/share/jupyter/runtime/nbserver-8699-open.html
    Or copy and paste one of these URLs:
        http://localhost:8891/?token=df61f3bd9880bc43743354760bb3a8673248cdcaa2329f7a
     or http://127.0.0.1:8891/?token=df61f3bd9880bc43743354760bb3a8673248cdcaa2329f7a
</pre>
</details>

**Comment by tedmoorman** [comment]
It was a port forwarding issue.  `gator --no-browser --port=xxxx --notebook-dir jupyter-folder` did the trick.

**Comment by fcollonval** [comment]
Thanks for providing the fix @tedmoorman - closing this as answered.
