### ISSUE TITLE
Add graph visualization

### ISSUE THREAD

**Issue by jtpio** [mamba-org/gator#83]
## Description

It would be nice to have an extra widget with the visualization from https://github.com/mamba-org/mamba-navigator/pull/5.

![third_cv_comp](https://user-images.githubusercontent.com/2227806/86028276-fe401d80-ba31-11ea-8f13-c7fbbc3ed79d.png)

For reference the component was defined here:

https://github.com/mamba-org/mamba-navigator/blob/84a3d5a700b30017112d68b98fdd7e63adc9f182/src/components/Network.vue

**Comment by fcollonval** [comment]
Closing as implemented in #102
