### ISSUE TITLE
Update to JupyterLab 3.0

### ISSUE THREAD

**Issue by jtpio** [mamba-org/gator#89]
Now that JupyterLab 3.0.0rc4 is available on both PyPI and conda forge, we can start updating both the labextension and the navigator to the 3.0 packages.

We should also look into packaging the labextension and the navigator as part of `jupyter_conda`.

**Comment by jtpio** [comment]
> as part of `jupyter_conda`.

Or a different name depending on https://github.com/mamba-org/jupyter_conda/issues/88

**Comment by fcollonval** [comment]
Thanks for taking care of that. I'm working this weekend on a better integration of the code. I think it will be worthy to wait for that before migrating to JLab 3.

**Comment by jtpio** [comment]
Ah nice, thanks @fcollonval.

https://github.com/mamba-org/jupyter_conda/pull/90 should have most of the things in place for JupyterLab 3.0 (except the navigator for now). Let me know if you want to pick it up after.
